version: "3"
services:
    backend:
        build:
            context: .
            dockerfile: ./Dockerfile-backend
        ports:
            - "9099:8099"
        volumes:
            - ../oiva-template:/opt/oiva/template
        depends_on:
            - "postgres"
            - "redis"
        networks:
            - oivanw
    postgres:
        image: postgres:9.6
        ports:
            - "6432:5432"
        environment:
            POSTGRES_USER: oiva
            POSTGRES_PASSWORD: oiva
            POSTGRES_DB: oiva
        networks:
            - oivanw
    redis:
        image: redis
        ports:
            - "7379:6379"
        networks:
            - oivanw
    nginx:
        hostname: localhost
        image: ficusio/openresty:latest
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/opt/openresty/nginx/conf/nginx.conf
            - ./nginx/ssl/nginx.crt:/opt/openresty/nginx/conf/ssl/nginx.crt
            - ./nginx/ssl/nginx.key:/opt/openresty/nginx/conf/ssl/nginx.key
        extra_hosts:
            hostmachine: HOSTIP
        networks:
            - oivanw
networks:
    oivanw:
        ipam:
            driver: default
            config:
                - subnet: 10.20.20.10/24