version: "3"
services:
    amos-backend:
        build:
            context: .
            dockerfile: ./Dockerfile-amos-backend
        ports:
            - "9099:8099"
        volumes:
            - ../oiva-template:/opt/oiva/template
        depends_on:
            - "amos-postgres"
            - "amos-redis"
        networks:
            - vpnsafe
    yva-backend:
        build:
            context: .
            dockerfile: ./Dockerfile-yva-backend
        ports:
            - "9100:8099"
        volumes:
            - ../oiva-template:/opt/oiva/template
        depends_on:
            - "yva-postgres"
            - "yva-redis"
        networks:
            - vpnsafe
    amos-postgres:
        build:
            context: .
            dockerfile: ./Dockerfile-postgres
        ports:
            - "6432:5432"
        environment:
            POSTGRES_USER: oiva
            POSTGRES_PASSWORD: oiva
            POSTGRES_DB: oiva
        networks:
            - vpnsafe
    yva-postgres:
        build:
            context: .
            dockerfile: ./Dockerfile-postgres
        ports:
            - "7432:5432"
        environment:
            POSTGRES_USER: kuja
            POSTGRES_PASSWORD: kuja
            POSTGRES_DB: kuja
        networks:
            - vpnsafe
    amos-redis:
        image: redis
        ports:
            - "7379:6379"
        networks:
            - vpnsafe
    yva-redis:
        image: redis
        ports:
            - "8379:6379"
        networks:
            - vpnsafe
    nginx:
        hostname: localhost
        image: ficusio/openresty:latest
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/opt/openresty/nginx/conf/nginx.conf
            - ./nginx/ssl/nginx.crt:/opt/openresty/nginx/conf/ssl/nginx.crt
            - ./nginx/ssl/nginx.key:/opt/openresty/nginx/conf/ssl/nginx.key
        extra_hosts:
            hostmachine: HOSTIP
        networks:
            - vpnsafe
networks:
    vpnsafe:
        ipam:
            driver: default
            config:
                - subnet: 10.20.23.10/24