# In servers and development these are overidden
# by external application.yml

oiva:
    dbhost: override_this_in_local_application_yml
    dbport: override_this_in_local_application_yml
    dbname: override_this_in_local_application_yml
    dbusername: override_this_in_local_application_yml
    dbpassword: override_this_in_local_application_yml
    baseUrl: override_this_in_local_application_yml

jooq:
    sql.dialect: POSTGRES

api:
    url.prefix: /api
    basicauth:
        username: override_this_in_local_application_yml
        password: override_this_in_local_application_yml

opintopolku:
    baseUrl: override_this_in_local_application_yml
    lokalisaatio:
        restUrl: /lokalisointi/cxf/rest/v1/localisation
    koodisto:
        restUrl: /koodisto-service/rest/json
    organisaatio:
        restUrl: /organisaatio-service/rest/organisaatio
    kayttooikeus:
        restUrl: /kayttooikeus-service
    apiCredentials:
        username: override_this_in_local_application_yml
        password: override_this_in_local_application_yml
    apiCaller:
        header: Caller-Id
        id: 1.2.246.562.10.78946234170.oiva

koulutustyyppi:
  ammatillinen:
    koodiarvot: 1,5,11,12,18,19

tutkintotyyppi:
  ammatillinen:
    koodiarvot: 02,19,20

cas:
    baseUrl: override_this_in_local_application_yml
    url.prefix: /cas
    url.login: /login
    url.logout: /logout
    service.url: /login/cas

multipart:
    maxFileSize: 512MB
    maxRequestSize: 512MB

server:
    port: override_this_in_local_application_yml
    tomcat:
        remote_ip_header: x-forwarded-for
        protocol_header: x-forwarded-proto

management:
    context-path: /manage
    security.enabled: false

spring:
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://${oiva.dbhost}:${oiva.dbport}/${oiva.dbname}?currentSchema=oiva
        username: ${oiva.dbusername}
        password: ${oiva.dbpassword}
        platform: postgresql
        driverClassName: org.postgresql.Driver
        initialize: false
    mvc:
      async:
        request-timeout: 60000 # Async request timeout 60 seconds.

    http:
      multipart:
        max-file-size: 25MB
        max-request-size: 25MB

redis:
    host: override_this_in_local_application_yml
    port: override_this_in_local_application_yml
    userSessionPrefix: spring:session
    refreshOnStartup: true

prince:
    exec.path: /usr/bin/prince

templates:
    base.path: /opt/oiva/template

file.storage:
    base.path: /opt/oiva/files

support:
    api.enabled: false

logging:
    path: /var/log/oiva
    file: ${logging.path}/oiva-backend.log
    level:
        root: WARN
        fi.minedu.oiva: INFO
        org.springframework.security: WARN
        org.jasig.cas.client.validation: WARN